/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jeanderson.br.interfaces;

import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import jeanderson.br.bugs.Relatar;
import jeanderson.br.main.Main;

/**
 *
 * @author Jeanderson S.Lopes
 */
public class TelaNovi extends javax.swing.JDialog {

    private int fundosQuantidade = 0;
    private int contador = 0;
    private ImageIcon imagem;
    private Main main;

    /**
     * Creates new form TelaNovi
     */
    public TelaNovi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        pegaInformacoes();
    }

    private void pegaInformacoes() {
        File imgQuantidade = new File("/Users/" + System.getProperty("user.name") + "/Google Drive/Aplicativo/System/Media/Fundos/");
        fundosQuantidade = (imgQuantidade.listFiles().length - 1);
        imagem = new ImageIcon("/Users/" + System.getProperty("user.name") + "/Google Drive/Aplicativo/System/Media/Fundos/" + contador + ".jpg");
        jlFundo.setIcon(new ImageIcon(imagem.getImage().getScaledInstance(835, 520, Image.SCALE_SMOOTH)));
        btnAnterior.setEnabled(false);
    }

    private void proximo() {
        contador++;
        imagem = new ImageIcon("/Users/" + System.getProperty("user.name") + "/Google Drive/Aplicativo/System/Media/Fundos/" + contador + ".jpg");
        jlFundo.setIcon(new ImageIcon(imagem.getImage().getScaledInstance(835, 520, Image.SCALE_SMOOTH)));
        btnAnterior.setEnabled(true);
    }

    private void anterior() {
        contador--;
        imagem = new ImageIcon("/Users/" + System.getProperty("user.name") + "/Google Drive/Aplicativo/System/Media/Fundos/" + contador + ".jpg");
        jlFundo.setIcon(new ImageIcon(imagem.getImage().getScaledInstance(835, 520, Image.SCALE_SMOOTH)));
        btnProximo.setEnabled(true);

    }

    public boolean verificarArquivos() {
        File arquivo = new File("/Users/" + System.getProperty("user.name") + "/Google Drive/Aplicativo/System/Media/Fundos/Quantidade.txt");
        int quantidade = 0;
        try {
            FileReader leitor = new FileReader(arquivo);
            BufferedReader ler = new BufferedReader(leitor);
            quantidade = Integer.parseInt(ler.readLine());
            ler.close();
            if (quantidade != fundosQuantidade) {
                return true;
            }
        } catch (FileNotFoundException ex) {
            Relatar.bug(TelaNovi.class.getName(), ex.toString());
            Logger.getLogger(TelaNovi.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Relatar.bug(TelaNovi.class.getName(), ex.toString());
            Logger.getLogger(TelaNovi.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jlFundo = new javax.swing.JLabel();
        btnAnterior = new javax.swing.JButton();
        btnProximo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Atualização Concluída");
        setAlwaysOnTop(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Novidades da Versão");

        jlFundo.setBackground(new java.awt.Color(255, 255, 255));
        jlFundo.setAutoscrolls(true);

        btnAnterior.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAnterior.setText("<<Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnProximo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnProximo.setText("Proximo>>");
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(334, 334, 334))
            .addGroup(layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(btnAnterior)
                .addGap(151, 151, 151)
                .addComponent(btnProximo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnterior)
                    .addComponent(btnProximo))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        anterior();
        if (contador == 0) {
            btnAnterior.setEnabled(false);
        } else {
            btnProximo.setEnabled(true);
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        proximo();
        if (contador == (fundosQuantidade - 1)) {
            btnProximo.setEnabled(false);
            main = new Main();
            main.pararSom();
            Main.setViuVideo(true);
            Main.verVideo();
        } else {
            btnAnterior.setEnabled(true);
        }
    }//GEN-LAST:event_btnProximoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaNovi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaNovi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaNovi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaNovi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaNovi dialog = new TelaNovi(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnProximo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlFundo;
    // End of variables declaration//GEN-END:variables
}
