/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jeanderson.br.interfaces;

import javax.swing.JOptionPane;
import jeanderson.br.bugs.Relatar;
import jeanderson.br.funcoes.Funcionalidades;
import jeanderson.br.main.Main;
import jeanderson.br.seguranca.Seguranca;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class TelaCadastro extends javax.swing.JDialog {
    private TelaSeguranca ts;
    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(507, 463);
        recebeIntancia();
    }
    private void recebeIntancia(){
        ts = new TelaSeguranca();
    }
    private void cadastrar(){
        if(txtAdmin.getText().trim().equals(ts.getUsuario().getUserAdmin()) && txtSenhaAdmin.getText().trim().equals(ts.getUsuario().getPasswordAdmin())){
            Seguranca usuario = new Seguranca(txtUsuario.getText().trim(), txtSenha.getText().trim());
            Funcionalidades.gerarSeguranca(usuario);
            Main.recebeUsuario(txtUsuario.getText().trim(), txtSenha.getText().trim());
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(rootPane, "ADMIN ou SenhaAdmin estão incorretos", "Incorretos", JOptionPane.WARNING_MESSAGE);
        }
    }
    private boolean verificarCampos(){
        if(txtUsuario.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Campo Usuario não preenchido", "Nao preenchido", JOptionPane.WARNING_MESSAGE);
            return true;
        }
        if(txtSenha.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Campo Senha não preenchido", "Nao preenchido", JOptionPane.WARNING_MESSAGE);
            return true;
        }
        if(txtAdmin.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Campo ADMIN não preenchido", "Nao preenchido", JOptionPane.WARNING_MESSAGE);
            return true;
        }
        if(txtSenhaAdmin.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Campo SenhaAdmin não preenchido", "Nao preenchido", JOptionPane.WARNING_MESSAGE);
            return true;
        }
        return false;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAdmin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSenhaAdmin = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        btnCadastrar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("ATENÇÃO: 1º Informe o ADMIN e a senhaAdmin fornecida pelo administrador do Sistema");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 487, 15);

        jLabel2.setText("ADMIN");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(250, 40, 60, 14);
        getContentPane().add(txtAdmin);
        txtAdmin.setBounds(120, 60, 276, 28);

        jLabel3.setText("SenhaADMIN");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(230, 100, 110, 14);
        getContentPane().add(txtSenhaAdmin);
        txtSenhaAdmin.setBounds(120, 130, 276, 28);

        jLabel4.setText("Escolha agora um Usuario e senha para sua conta");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(140, 170, 370, 14);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Usuario:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(240, 200, 43, 15);
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(120, 220, 276, 28);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Senha:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(240, 250, 38, 15);
        getContentPane().add(txtSenha);
        txtSenha.setBounds(120, 270, 276, 28);

        btnCadastrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCadastrar.setText("Concluir Cadastro");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(120, 320, 141, 25);

        btnLimpar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLimpar.setText("Limpar");
        getContentPane().add(btnLimpar);
        btnLimpar.setBounds(330, 320, 73, 25);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jeanderson/br/imagens/face.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 510, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        if(verificarCampos()){
            return;
        }
        cadastrar();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaCadastro dialog = new TelaCadastro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtAdmin;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JPasswordField txtSenhaAdmin;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
