/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jeanderson.br.interfaces;

import jeanderson.br.main.Main;

/**
 *
 * @author Jeanderson S.Lopes
 */
public class TelaDetalhe extends javax.swing.JDialog {

    private boolean editou = false;
    private int posicao = 0;

    /**
     * Creates new form TelaDetalhe
     */
    public TelaDetalhe(java.awt.Frame parent, boolean modal, int posicao) {
        super(parent, modal);
        initComponents();
        setSize(560, 540);
        preencherDesc(posicao);
    }

    private void preencherDesc(int posicao) {
        this.posicao = posicao;
        Main main = new Main();
        txtNome.setEditable(false);
        txtQuantidade.setEditable(false);
        txtValor.setEditable(false);
        txtDescricao.setEditable(false);
        txtNome.setText(main.getEstoque().get(posicao).getNome());
        txtQuantidade.setText(Integer.toString(main.getEstoque().get(posicao).getQuantidade()));
        txtValor.setText(Double.toString(main.getEstoque().get(posicao).getValor()));
        txtDescricao.setText(main.getEstoque().get(posicao).getDescricao());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        btnVoltar = new javax.swing.JButton();
        btnDescrição = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Produto:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 15, 55, 17);
        getContentPane().add(txtNome);
        txtNome.setBounds(89, 11, 387, 28);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Quantidade:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 49, 75, 17);
        getContentPane().add(txtQuantidade);
        txtQuantidade.setBounds(89, 45, 61, 28);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Valor(R$) UN:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(198, 49, 84, 17);
        getContentPane().add(txtValor);
        txtValor.setBounds(286, 45, 92, 28);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Descrição do Produto:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(213, 91, 138, 17);

        txtDescricao.setColumns(20);
        txtDescricao.setLineWrap(true);
        txtDescricao.setRows(5);
        txtDescricao.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtDescricao);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(89, 114, 387, 288);

        btnVoltar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar);
        btnVoltar.setBounds(89, 413, 80, 25);

        btnDescrição.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDescrição.setText("Editar Descrição");
        btnDescrição.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescriçãoActionPerformed(evt);
            }
        });
        getContentPane().add(btnDescrição);
        btnDescrição.setBounds(293, 410, 180, 25);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jeanderson/br/imagens/5.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 560, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnDescriçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescriçãoActionPerformed
        if (!editou) {
            txtDescricao.setEditable(true);
            editou = true;
            btnDescrição.setText("Concluir Alteração");
        } else {
            Main main = new Main();
            main.getEstoque().get(posicao).setDescricao(txtDescricao.getText());
            main.atualizarBanco();
            editou = false;
            btnDescrição.setText("Editar Descrição");
            txtDescricao.setEditable(false);
        }
    }//GEN-LAST:event_btnDescriçãoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDetalhe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDetalhe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDetalhe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDetalhe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaDetalhe dialog = new TelaDetalhe(new javax.swing.JFrame(), true, 0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDescrição;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
