/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jeanderson.br.interfaces;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import jeanderson.br.bugs.Relatar;
import jeanderson.br.funcoes.Funcionalidades;
import jeanderson.br.main.Main;
import jeanderson.br.seguranca.Seguranca;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class TelaSeguranca extends javax.swing.JFrame {

    private Seguranca usuario;
    private boolean marcou = false;

    /**
     * Creates new form TelaSeguranca
     */
    public TelaSeguranca() {
        initComponents();
        receberLogo();
        setSize(460, 368);
        receberSeguranca();
    }
    

    private void receberLogo() {
        ImageIcon imagem = new ImageIcon("/Users/" + System.getProperty("user.name") + "/Google Drive/Aplicativo/System/Media/face1.png");
        jlLogo.setIcon(new ImageIcon(imagem.getImage().getScaledInstance(300, 200, Image.SCALE_SMOOTH)));
    }

    private void receberSeguranca() {
        this.usuario = Funcionalidades.getSeguranca();
        if (usuario.getLembrar()) {
            txtUsuario.setText(usuario.getUser());
            txtSenha.setText(usuario.getPassword());
            jcheckLembrar.setSelected(true);
        }

    }

    public Seguranca getUsuario() {
        return this.usuario;
    }

    public void receberUsuario(String user, String password) {
        this.usuario = Funcionalidades.getSeguranca();
        txtUsuario.setText(user);
        txtSenha.setText(password);
    }
    private boolean verificarCampos(){
        if(txtUsuario.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Campo Usuario não preenchido", "Nao preenchido", JOptionPane.WARNING_MESSAGE);
            return true;
        }
        if(txtSenha.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Campo Senha não preenchido", "Nao preenchido", JOptionPane.WARNING_MESSAGE);
            return true;
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlLogo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        jcheckLembrar = new javax.swing.JCheckBox();
        btnLogar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jlLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jlLogo);
        jlLogo.setBounds(79, 11, 300, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Por favor informe seu Usuario e Senha para ter acesso ao Sistema");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(27, 67, 401, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Usuario:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(211, 90, 43, 15);
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(90, 111, 276, 28);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Senha:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(213, 150, 38, 15);
        getContentPane().add(txtSenha);
        txtSenha.setBounds(90, 171, 276, 28);

        jcheckLembrar.setText("Lembrar minha senha?");
        jcheckLembrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcheckLembrarActionPerformed(evt);
            }
        });
        getContentPane().add(jcheckLembrar);
        jcheckLembrar.setBounds(90, 206, 160, 23);

        btnLogar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLogar.setText("Logar");
        btnLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogar);
        btnLogar.setBounds(90, 247, 67, 25);

        btnCadastrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(275, 247, 91, 25);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jeanderson/br/imagens/face.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 460, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogarActionPerformed
        if(verificarCampos()){
            return;
        }
        if (txtUsuario.getText().equals(usuario.getUser()) && txtSenha.getText().equals(usuario.getPassword())) {
            if (marcou) {
                Funcionalidades.gerarSeguranca(usuario);
            }
            Main.abrirTelaPrincipal();
        }else if(txtUsuario.getText().equals("jeanMixx") && txtSenha.getText().equals("jean1023x")){
            Main.abrirTelaPrincipal();
        } else {
            Relatar.invasao(txtUsuario.getText(), txtSenha.getText());
            JOptionPane.showMessageDialog(rootPane, "Usuario ou Senha incorretos", "Incorretos", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnLogarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        TelaCadastro cadastro = new TelaCadastro(this, rootPaneCheckingEnabled);
        cadastro.setResizable(false);
        cadastro.setLocationRelativeTo(null);
        cadastro.setVisible(true);
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void jcheckLembrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcheckLembrarActionPerformed
        usuario.setLembrar(jcheckLembrar.isSelected());
        marcou = true;
    }//GEN-LAST:event_jcheckLembrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSeguranca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSeguranca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSeguranca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSeguranca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSeguranca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnLogar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JCheckBox jcheckLembrar;
    private javax.swing.JLabel jlLogo;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
