/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jeanderson.br.interfacesV2;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import jeanderson.br.backups.Backup;
import jeanderson.br.bugs.Relatar;
import jeanderson.br.interfaces.TelaNovi;
import jeanderson.br.interfaces.TelaTuto;
import jeanderson.br.main.Main;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private TelaAdiciona adiciona;
    private TelaMostra mostra;
    private TelaAddCliente addCliente;
    private TelaClientes clientes;
    private TelaNotas notas;
    private TelaConfig config;
    private TelaNotasRecebidas notasRecebidas;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        pegarResolucao();
        adiciona = new TelaAdiciona();
        mostra = new TelaMostra();
        addCliente = new TelaAddCliente();
        clientes = new TelaClientes();
        notas = new TelaNotas();
        config = new TelaConfig();
        notasRecebidas = new TelaNotasRecebidas();
    }

    private void pegarResolucao() {
        Toolkit t = Toolkit.getDefaultToolkit();
        Dimension dimensao = t.getScreenSize();
        setSize((dimensao.width + 5), (dimensao.height - 40));
        this.setSize((dimensao.width + 5), (dimensao.height - 38));
        //aqui já muda a Skin das interfaces.
//        try {
//            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
//        } catch (ClassNotFoundException ex) {
//            Relatar.bug(TelaPrincipal.class.getName(), ex.toString());
//            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            Relatar.bug(TelaPrincipal.class.getName(), ex.toString());
//            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            Relatar.bug(TelaPrincipal.class.getName(), ex.toString());
//            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (UnsupportedLookAndFeelException ex) {
//            Relatar.bug(TelaPrincipal.class.getName(), ex.toString());
//            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
//        }

    }

    public void atualizaTabela() {
        if (mostra.isVisible()) {
            mostra.preencherTabela();
        }
    }

    public void abrirTelaNota(String iD, String produto, String quantidade, String valor) {
        if (notas.isVisible()) {
            notas.addProduto(iD, produto, quantidade, valor);
        } else {
            jdpArea.add(notas);
            notas.setVisible(true);
            notas.listaClientes();
            notas.addProduto(iD, produto, quantidade, valor);
        }
    }

    public void abrirTelaNotasRecebidas() {
        if (notasRecebidas.isVisible()) {
            notasRecebidas.recebeNotas();
        } else {
            jdpArea.add(notasRecebidas);
            notasRecebidas.recebeNotas();
            notasRecebidas.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpArea = new JDesktopPane(){
            Image fundo = new ImageIcon("/Users/"+System.getProperty("user.name")+"/Google Drive/Aplicativo/System/Media/Fundo.jpg").getImage();
            @Override
            protected void paintComponent(Graphics g)
            {
                g.drawImage(fundo,0,0,getWidth(),getHeight(),null);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jmVerGrafico = new javax.swing.JMenuItem();
        jmRestaurar = new javax.swing.JMenuItem();
        jmFazerBackup = new javax.swing.JMenuItem();
        jmConfig = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmSair = new javax.swing.JMenuItem();
        mMostrar = new javax.swing.JMenu();
        jmAdicionarProduto = new javax.swing.JMenuItem();
        jmMostrar = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jmCadastrar = new javax.swing.JMenuItem();
        jmClientes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu3.setText("Opções");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jmVerGrafico.setText("Ver Gráficos");
        jmVerGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmVerGraficoActionPerformed(evt);
            }
        });
        jMenu3.add(jmVerGrafico);

        jmRestaurar.setText("Restaurar Backup");
        jmRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmRestaurarActionPerformed(evt);
            }
        });
        jMenu3.add(jmRestaurar);

        jmFazerBackup.setText("Fazer Backup");
        jmFazerBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFazerBackupActionPerformed(evt);
            }
        });
        jMenu3.add(jmFazerBackup);

        jmConfig.setText("Configuração");
        jmConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmConfigActionPerformed(evt);
            }
        });
        jMenu3.add(jmConfig);

        jMenuItem1.setText("Ver Tutorial");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jmSair.setText("Sair");
        jmSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSairActionPerformed(evt);
            }
        });
        jMenu3.add(jmSair);

        jMenuBar1.add(jMenu3);

        mMostrar.setText("Meu Estoque");
        mMostrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jmAdicionarProduto.setText("Adicionar Produto");
        jmAdicionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAdicionarProdutoActionPerformed(evt);
            }
        });
        mMostrar.add(jmAdicionarProduto);

        jmMostrar.setText("Mostrar Estoque");
        jmMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMostrarActionPerformed(evt);
            }
        });
        mMostrar.add(jmMostrar);

        jMenuBar1.add(mMostrar);

        jMenu5.setText("Cadastros");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jmCadastrar.setText("Cadastrar Clientes");
        jmCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadastrarActionPerformed(evt);
            }
        });
        jMenu5.add(jmCadastrar);

        jmClientes.setText("Clientes Cadastrados");
        jmClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmClientesActionPerformed(evt);
            }
        });
        jMenu5.add(jmClientes);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpArea, javax.swing.GroupLayout.DEFAULT_SIZE, 1600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpArea, javax.swing.GroupLayout.DEFAULT_SIZE, 878, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmAdicionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAdicionarProdutoActionPerformed
        if (!adiciona.isVisible()) {
            jdpArea.add(adiciona);
            adiciona.setVisible(true);
        }
    }//GEN-LAST:event_jmAdicionarProdutoActionPerformed

    private void jmMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMostrarActionPerformed
        if (!mostra.isVisible()) {
            mostra.preencherTabela();
            jdpArea.add(mostra);
            mostra.setVisible(true);
        }
    }//GEN-LAST:event_jmMostrarActionPerformed

    private void jmCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadastrarActionPerformed
        if (!addCliente.isVisible()) {
            jdpArea.add(addCliente);
            addCliente.setVisible(true);
        }
    }//GEN-LAST:event_jmCadastrarActionPerformed

    private void jmClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmClientesActionPerformed
        if (!clientes.isVisible()) {
            jdpArea.add(clientes);
            clientes.setVisible(true);
            clientes.listaDeClientes();
        }
    }//GEN-LAST:event_jmClientesActionPerformed

    private void jmRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmRestaurarActionPerformed
        Backup.retornarBackup();
        Main main = new Main();
        main.receberProduto();
        JOptionPane.showMessageDialog(rootPane, "Backup Restaurado com Sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jmRestaurarActionPerformed

    private void jmFazerBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFazerBackupActionPerformed
        Backup.fazerBackup();
        JOptionPane.showMessageDialog(rootPane, "Backup Feito com Sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jmFazerBackupActionPerformed

    private void jmVerGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmVerGraficoActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Não disponível nessa versão", "Não Disponível", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jmVerGraficoActionPerformed

    private void jmConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmConfigActionPerformed
        if (!config.isVisible()) {
            jdpArea.add(config);
            config.setVisible(true);
        }
    }//GEN-LAST:event_jmConfigActionPerformed

    private void jmSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmSairActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        TelaTuto tutorial = new TelaTuto(this, rootPaneCheckingEnabled);
        tutorial.setResizable(false);
        tutorial.setLocationRelativeTo(null);
        tutorial.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JDesktopPane jdpArea;
    private javax.swing.JMenuItem jmAdicionarProduto;
    private javax.swing.JMenuItem jmCadastrar;
    private javax.swing.JMenuItem jmClientes;
    private javax.swing.JMenuItem jmConfig;
    private javax.swing.JMenuItem jmFazerBackup;
    private javax.swing.JMenuItem jmMostrar;
    private javax.swing.JMenuItem jmRestaurar;
    private javax.swing.JMenuItem jmSair;
    private javax.swing.JMenuItem jmVerGrafico;
    private javax.swing.JMenu mMostrar;
    // End of variables declaration//GEN-END:variables
}
