/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jeanderson.br.interfacesV2;

import javax.swing.JOptionPane;
import jeanderson.br.cliente.Clientes;
import jeanderson.br.main.Main;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class TelaAddCliente extends javax.swing.JInternalFrame {

    private Main main;

    /**
     * Creates new form TelaAddCliente
     */
    public TelaAddCliente() {
        initComponents();
        main = new Main();
        setSize(584, 418);
    }

    private boolean verificarCampos() {
        if (txtNome.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Campo NOME não preenchido corretamente", "ERRO", JOptionPane.WARNING_MESSAGE);
            return true;
        }
        if (txtEndereco.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Campo ENDEREÇO não preenchido corretamente", "ERRO", JOptionPane.WARNING_MESSAGE);
            return true;
        }
        if (txtEmail.getText().trim().isEmpty()) {
            txtEmail.setText("semEmail@email.com");
        }
        if (txtCpf.getText().trim().isEmpty()) {
            txtCpf.setText("CPF não cadastrado");
        }
        if (txtCidade.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Campo CIDADE não preenchido corretamente", "ERRO", JOptionPane.WARNING_MESSAGE);
            return true;
        }
        if (txtUf.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Campo UF não preenchido corretamente", "ERRO", JOptionPane.WARNING_MESSAGE);
            return true;
        }
        if (txtBairro.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Campo BAIRRO não preenchido corretamente", "ERRO", JOptionPane.WARNING_MESSAGE);
            return true;
        }
        return false;
    }

    private void limparCampos() {
        txtBairro.setText(null);
        txtCidade.setText(null);
        txtCpf.setText(null);
        txtEmail.setText(null);
        txtEndereco.setText(null);
        txtNome.setText(null);
        txtUf.setText(null);
        txtNome.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtUf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de Clientes");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 25, 36, 15);
        getContentPane().add(txtNome);
        txtNome.setBounds(70, 19, 413, 28);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("CPF:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(42, 59, 24, 15);
        getContentPane().add(txtCpf);
        txtCpf.setBounds(70, 53, 187, 28);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel3.setText("Obs: Não é Obrigatorio preencher o campo CPF.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(261, 61, 222, 13);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Endereço:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 93, 56, 15);
        getContentPane().add(txtEndereco);
        txtEndereco.setBounds(70, 87, 413, 28);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Bairro:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(32, 132, 34, 15);
        getContentPane().add(txtBairro);
        txtBairro.setBounds(70, 126, 187, 28);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Cidade:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(26, 166, 40, 15);
        getContentPane().add(txtCidade);
        txtCidade.setBounds(70, 160, 334, 28);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("UF:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(414, 166, 18, 15);
        getContentPane().add(txtUf);
        txtUf.setBounds(436, 160, 47, 28);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Email:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(35, 205, 31, 15);
        getContentPane().add(txtEmail);
        txtEmail.setBounds(70, 199, 187, 28);

        btnCadastrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(70, 256, 91, 25);

        btnLimpar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLimpar.setText("Limpar Tudo");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar);
        btnLimpar.setBounds(374, 256, 109, 25);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jeanderson/br/imagens/8.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 580, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        if (verificarCampos()) {
            return;
        }
        Clientes clientes = new Clientes(txtNome.getText(), txtCpf.getText(), txtEmail.getText(), txtEndereco.getText(), txtCidade.getText(), txtUf.getText(), txtBairro.getText());
        if (!main.adicionarCliente(clientes)) {
            main.atualizarListaClientes();
            limparCampos();
            JOptionPane.showMessageDialog(rootPane, "Cliente Cadastrado com Sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Já existe este Cliente Cadastrado", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtUf;
    // End of variables declaration//GEN-END:variables
}
